services:

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SERVER_HTTP_PORT=${GRAFANA_PORT}
    env_file:
      - .env
  
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGPORT=${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/src/:/backend/src
      - ./backend/src/static/uploads/:/backend/src/static/uploads
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - UVICORN_PORT=${BACKEND_PORT}
    env_file:
      - .env
      
  frontend:
    build: ./frontend
    container_name: frontend
    ports: 
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - PORT=${FRONTEND_PORT}
    env_file:
      .env