apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${DATABASE_USER}
    database: ${DATABASE_NAME}
    jsonData:
      sslmode: "disable"
      maxOpenConns: 0
      maxIdleConns: 2
      postgresVersion: 1000
      timescaledb: false
    secureJsonData:
      password: ${DATABASE_PASSWORD}
    editable: true
