{
 "title": "Main Dashboard",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "Sensitividade Demográfica",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Questão 1",
     "type": "barchart",
     "description": "Como descreve a mobilidade de idosos e pessoas com dificuldade de locomoção em sua casa?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_1 as resposta,\r\n  COUNT(*) AS quantidade\r\nFROM forms\r\nWHERE\r\n  question_1 IS NOT NULL AND\r\n  $__timeFilter(date) \r\nGROUP BY question_1\r\n"
      }
     ]
    },
    {
     "title": "Questão 2",
     "type": "table",
     "description": "Existe alguma deficiência sensorial em algum habitante de sua casa?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_2 as resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_2 IS NOT NULL AND\r\n  $__timeFilter(date) \r\nGROUP BY question_2 "
      }
     ]
    },
    {
     "title": "Questão 3",
     "type": "table",
     "description": "Existe alguma deficiência sensorial em algum habitante da sua casa?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_3 as resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_3 IS NOT NULL AND\r\n  $__timeFilter(date) \r\nGROUP BY question_3"
      }
     ]
    },
    {
     "title": "Questão 4",
     "type": "table",
     "description": "Algum outro agravo de saúde que atrapalhe a evacuação em situação de emergência?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_4 as resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_4 IS NOT NULL AND\r\n  $__timeFilter(date) \r\nGROUP BY question_4"
      }
     ]
    },
    {
     "title": "Questão 5",
     "type": "table",
     "description": "Alguém da sua casa faleceu por conta da COVID 19?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_5 as resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_5 IS NOT NULL AND\r\n  $__timeFilter(date) \r\nGROUP BY question_5"
      }
     ]
    },
    {
     "title": "Questão 6",
     "type": "table",
     "description": "A pandemia de COVID 19 afetou a renda da sua residência?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_6,\r\n  COUNT(*)\r\nFROM forms\r\nWHERE \r\n  question_6 IS NOT NULL AND\r\n  $__timeFilter(date) \r\nGROUP BY question_6"
      }
     ]
    }
   ]
  },
  {
   "title": "Moradores",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sexo",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  sex as sexo,\r\n  COUNT(*) as quantidade\r\nFROM residents\r\nJOIN forms ON residents.form_id = forms.id\r\nWHERE\r\n  sex IS NOT NULL AND\r\n  sex in ('M', 'F') AND\r\n  $__timeFilter(date) \r\nGROUP BY sex"
      }
     ]
    },
    {
     "title": "Idade",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  age as idade,\r\n  COUNT(*) as quantidade\r\nFROM residents\r\nJOIN forms ON residents.form_id = forms.id\r\nWHERE\r\n  age IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY age\r\n\r\n"
      }
     ]
    },
    {
     "title": "Deficiência Sensorial",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  sensory_impairment as deficiência,\r\n  COUNT(*) as quantidade\r\nFROM residents\r\nJOIN forms ON residents.form_id = forms.id\r\nWHERE\r\n  sensory_impairment IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY sensory_impairment\r\n\r\n"
      }
     ]
    },
    {
     "title": "Restrição de Mobilidade",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  mobility_restriction as restricao,\r\n  COUNT(*) as quantidade\r\nFROM residents\r\nJOIN forms ON residents.form_id = forms.id\r\nWHERE\r\n  mobility_restriction IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY mobility_restriction\r\n\r\n"
      }
     ]
    },
    {
     "title": "Agravo de Saúde",
     "type": "table",
     "description": "Algum outro agravo de saúde que atrapalhe a evacuação em situação de emergência",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  health_injury as agravo,\r\n  COUNT(*) as quantidade\r\nFROM residents\r\nJOIN forms ON residents.form_id = forms.id\r\nWHERE\r\n  health_injury IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY health_injury\r\n\r\n"
      }
     ]
    },
    {
     "title": "Portador de Transtorno / Deficiência Mental",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  mental_disorder as transtorno,\r\n  COUNT(*) as quantidade\r\nFROM residents\r\nJOIN forms ON residents.form_id = forms.id\r\nWHERE\r\n  mental_disorder IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY mental_disorder\r\n\r\n"
      }
     ]
    },
    {
     "title": "Educação",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  CASE\r\n      WHEN education IN ('ENSINO FUNDAMENTAL', 'FUNDAMENTAL') THEN 'ENSINO FUNDAMENTAL'\r\n      ELSE education\r\n  END AS parsed_education,\r\n  COUNT(*) as quantidade\r\nFROM residents\r\nJOIN forms ON residents.form_id = forms.id\r\nWHERE\r\n  education IN ('MÉDIO', 'FUNDAMENTAL', 'ENSINO FUNDAMENTAL', 'ENSINO MÉDIO', 'NENHUMA', 'FACULDADE') AND\r\n  $__timeFilter(date)\r\nGROUP BY parsed_education\r\n\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Preparação para Desastres",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Questão 7",
     "type": "table",
     "description": "Em caso de alarme chuva por sirene, sabe onde é o ponto de apoio da comunidade?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_7 as resposta,\r\n  COUNT(*) AS quantidade\r\nFROM forms\r\nWHERE\r\n  question_7 IS NOT NULL AND\r\n  $__timeFilter(date) \r\nGROUP BY question_7\r\n"
      }
     ]
    },
    {
     "title": "Questão 8",
     "type": "table",
     "description": "Em caso de alarme de chuva por sirene, qual o comportamento esperado?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_8 as resposta,\r\n  COUNT(*) AS quantidade\r\nFROM forms\r\nWHERE\r\n  question_8 IS NOT NULL AND\r\n  $__timeFilter(date) \r\nGROUP BY question_8\r\n"
      }
     ]
    },
    {
     "title": "Questão 9",
     "type": "table",
     "description": "Em caso de deslizamento de terra ou sinal de alerta, você conhece a rota de fuga mais próxima? Eles são seguros durante a chuva?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_9 as resposta,\r\n  COUNT(*) AS quantidade\r\nFROM forms\r\nWHERE\r\n  question_9 IS NOT NULL AND\r\n  $__timeFilter(date) \r\nGROUP BY question_9\r\n"
      }
     ]
    },
    {
     "title": "Questão 10",
     "type": "stat",
     "description": "De 0 a 10, qual o grau de confiança que possui no acionamento das sirenes?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  AVG(question_10) as confianca\r\nFROM forms\r\nWHERE\r\n  question_10 IS NOT NULL AND\r\n  $__timeFilter(date) \r\n"
      }
     ]
    },
    {
     "title": "Questão 11",
     "type": "stat",
     "description": "De 0 a 10, qual o grau de confiança que possui na Defesa Civil Municipal ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  AVG(question_11) as confianca\r\nFROM forms\r\nWHERE\r\n  question_11 IS NOT NULL AND\r\n  $__timeFilter(date) \r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Sensitividade das Construções e Habitações",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Questão 12",
     "type": "table",
     "description": "A casa (apartamento) tem acesso a infraestrutura pública?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_12_a AS rua_pavimentada,\r\n  question_12_b AS escada_de_concreto,\r\n  question_12_c AS fornecimento_de_agua\r\nFROM forms\r\nWHERE\r\n  question_12_a IS NOT NULL AND\r\n  question_12_b IS NOT NULL AND\r\n  question_12_c IS NOT NULL AND\r\n  $__timeFilter(date) "
      }
     ]
    },
    {
     "title": "Questão 13",
     "type": "table",
     "description": "Qual dos tipos de construção melhor descreve sua construção física e as condições de habitação? // Pegar uma descricao das alternativas e fazer um value mapping pra cada uma",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_13 as resposta,\r\n  COUNT(*) AS quantidade\r\nFROM forms\r\nWHERE\r\n  question_13 IS NOT NULL AND\r\n  $__timeFilter(date) \r\nGROUP BY question_13\r\n"
      }
     ]
    },
    {
     "title": "Questão 14",
     "type": "table",
     "description": "Dos seguintes materiais de construção, quais são os usados para construir: fundação da casa, paredes, teto, telhado e caixas d'água?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_14_1 AS fundacao,\r\n  question_14_2 AS piso,\r\n  question_14_3 AS colunas,\r\n  question_14_4 AS vergalhao_exposto,\r\n  question_14_5 as material_da_parede,\r\n  question_14_6 as viga_de_suporte_da_parede,\r\n  question_14_7 as telhado,\r\n  question_14_8 as colunas_de_suporte_do_telhado,\r\n  question_14_9 as manchas_de_mofo_nas_paredes_externas\r\nFROM forms\r\nWHERE\r\n  $__timeFilter(date) \r\n"
      }
     ]
    },
    {
     "title": "Questão 15",
     "type": "table",
     "description": "A sua estrutura habitacional corta uma inclinação ou está localizada no topo de um declive?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_15 as resposta,\r\n  COUNT(*) AS quantidade\r\nFROM forms\r\nWHERE\r\n  question_15 IS NOT NULL AND\r\n  $__timeFilter(date) \r\nGROUP BY question_15\r\n"
      }
     ]
    },
    {
     "title": "Questão 16",
     "type": "table",
     "description": "Qual condição geológica ou do solo no gradiente de encosta descreve melhor a situação real ao redor da casa?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_16 as resposta,\r\n  COUNT(*) AS quantidade\r\nFROM forms\r\nWHERE\r\n  question_16 IS NOT NULL AND\r\n  $__timeFilter(date) \r\nGROUP BY question_16\r\n"
      }
     ]
    },
    {
     "title": "Questão 17",
     "type": "table",
     "description": "Que tipo de vegetação pode ser observada perto da casa?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_17 as resposta,\r\n  COUNT(*) AS quantidade\r\nFROM forms\r\nWHERE\r\n  question_17 IS NOT NULL AND\r\n  $__timeFilter(date) \r\nGROUP BY question_17\r\n"
      }
     ]
    },
    {
     "title": "Questão 18",
     "type": "piechart",
     "description": "A construção foi erguida sobre curso d'agua ou talvegue?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_18 as value,\r\n  COUNT(*)\r\nFROM forms \r\nWHERE\r\n  question_18 IN ('sim',  'não') AND\r\n  $__timeFilter(date) \r\nGROUP BY question_18"
      }
     ]
    }
   ]
  },
  {
   "title": "Evidências de Movimentos dos Solos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Questão 19",
     "type": "table",
     "description": "Podem ser observados indícios de movimentação do solo na casa ou no terreno do entorno?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_19_1 AS trincas_na_fundacao_da_casa,\r\n  question_19_2 AS trincas_nas_paredes,\r\n  question_19_3 AS trincas_nos_pavimentos,\r\n  question_19_4 AS degraus_de_abatimento,\r\n  question_19_5 AS inclinacao_de_arvores_muros_ou_postes,\r\n  question_19_6 AS outros\r\nFROM forms\r\nWHERE\r\n  question_19_1 IS NOT NULL AND\r\n  question_19_2 IS NOT NULL AND\r\n  question_19_3 IS NOT NULL AND\r\n  question_19_4 IS NOT NULL AND\r\n  question_19_5 IS NOT NULL AND\r\n  question_19_6 IS NOT NULL AND\r\n  $__timeFilter(date)"
      }
     ]
    },
    {
     "title": "Questão 20",
     "type": "table",
     "description": "Em que direções essas trincas ocorrem?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_20_1 AS vertical,\r\n  question_20_1 AS horizontal,\r\n  question_20_1 AS diagonal\r\nFROM forms\r\nWHERE\r\n  question_20_1 IS NOT NULL AND\r\n  question_20_2 IS NOT NULL AND\r\n  question_20_3 IS NOT NULL AND\r\n  $__timeFilter(date) "
      }
     ]
    },
    {
     "title": "Questão 21",
     "type": "table",
     "description": "Existem muros ou paredes \"embarrigadas\"?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_21 as resposta,\r\n  COUNT(*) AS quantidade\r\nFROM forms\r\nWHERE\r\n  question_21 IS NOT NULL AND\r\n  $__timeFilter(date) \r\nGROUP BY question_21\r\n"
      }
     ]
    },
    {
     "title": "Questão 22",
     "type": "table",
     "description": "Existe histórico de deslizamentos?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_22 as resposta,\r\n  COUNT(*) AS quantidade\r\nFROM forms\r\nWHERE\r\n  question_22 IS NOT NULL AND\r\n  $__timeFilter(date) \r\nGROUP BY question_22\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Sensitividade Física / Caraterização da Encosta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Questão 23",
     "type": "table",
     "description": "Encosta Natural",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_23_1 AS possui,\r\n  question_23_2 AS altura,\r\n  question_23_3 AS inclinacao\r\nFROM forms\r\nWHERE\r\n  question_23_1 IS NOT NULL AND\r\n  $__timeFilter(date)"
      }
     ]
    },
    {
     "title": "Questão 24",
     "type": "table",
     "description": "Talude de Corte",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_24_1 AS possui,\r\n  question_24_2 AS altura,\r\n  question_24_3 AS inclinacao,\r\n  question_24_4 as distancia\r\nFROM forms\r\nWHERE\r\n  question_24_1 IS NOT NULL AND\r\n  $__timeFilter(date)"
      }
     ]
    },
    {
     "title": "Questão 25",
     "type": "table",
     "description": "Aterro Lançado",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_25_1 AS possui,\r\n  question_25_2 AS altura,\r\n  question_25_3 AS inclinacao,\r\n  question_25_4 as distancia\r\nFROM forms\r\nWHERE\r\n  question_25_1 IS NOT NULL AND\r\n  $__timeFilter(date)"
      }
     ]
    },
    {
     "title": "Questão 26",
     "type": "table",
     "description": "Presença de parede rochosa",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_26_1 AS possui,\r\n  question_26_2 AS altura,\r\n  question_26_3 AS inclinacao\r\nFROM forms\r\nWHERE\r\n  question_26_1 IS NOT NULL AND\r\n  $__timeFilter(date)"
      }
     ]
    }
   ]
  },
  {
   "title": "Saneamento",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Questão 27",
     "type": "table",
     "description": "Concentração de água de chuva em superfície (enxurrada)?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_27 AS resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_27 IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY question_27"
      }
     ]
    },
    {
     "title": "Questão 28",
     "type": "table",
     "description": "Lançamento de água servida em superfície (a céu aberto no quintal)?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_28 AS resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_28 IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY question_28"
      }
     ]
    },
    {
     "title": "Questão 29",
     "type": "table",
     "description": "A casa possui caixa d’água? ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_29 AS resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_29 IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY question_29"
      }
     ]
    },
    {
     "title": "Questão 30",
     "type": "table",
     "description": "30 Localização da caixa d’água?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_30 AS resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_30 IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY question_30"
      }
     ]
    },
    {
     "title": "Questão 31",
     "type": "table",
     "description": "Indícios de transbordamento?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_31 AS resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_31 IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY question_31"
      }
     ]
    },
    {
     "title": "Questão 32",
     "type": "table",
     "description": "De onde vem a sua água?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_32 AS resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_32 IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY question_32"
      }
     ]
    },
    {
     "title": "Questão 33",
     "type": "table",
     "description": " Onde o esgoto da casa é destinado?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_33 AS resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_33 IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY question_33"
      }
     ]
    },
    {
     "title": "Questão 34",
     "type": "table",
     "description": "Existe vazamento na tubulação?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_34 AS resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_34 IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY question_34"
      }
     ]
    },
    {
     "title": "Questão 35",
     "type": "table",
     "description": "Durante ou após a precipitação, a água aparece ou flui perto ou sobre sua propriedade? ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_35 AS resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_35 IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY question_35"
      }
     ]
    },
    {
     "title": "Questão 36",
     "type": "table",
     "description": " Minas d´água no barranco (talude)?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_36 AS resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_36 IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY question_36"
      }
     ]
    },
    {
     "title": "Questão 37",
     "type": "table",
     "description": "Quantos sacos de lixo por dia um residente da casa traz para fora de casa?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_37 AS resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_37 IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY question_37"
      }
     ]
    },
    {
     "title": "Questão 38",
     "type": "table",
     "description": "Onde as sacolas de lixo são colocadas? ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  question_38 AS resposta,\r\n  COUNT(*) as valor\r\nFROM forms\r\nWHERE\r\n  question_38 IS NOT NULL AND\r\n  $__timeFilter(date)\r\nGROUP BY question_38"
      }
     ]
    }
   ]
  }
 ]
}